name: Auto YouTube Upload

on:
  workflow_dispatch:

jobs:
  upload_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-auth google-auth-oauthlib google-api-python-client

      - name: Run upload script
        run: python .github/workflows/upload.py
