import os
import json
import google.auth.transport.requests
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# YouTube API scopes
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

# Load credentials from environment
creds = Credentials(
    None,
    refresh_token=os.environ["YT_REFRESH_TOKEN"],
    token_uri="https://oauth2.googleapis.com/token",
    client_id=os.environ["YT_CLIENT_ID"],
    client_secret=os.environ["YT_CLIENT_SECRET"],
    scopes=SCOPES,
)

# Refresh access token
creds.refresh(google.auth.transport.requests.Request())

# Build YouTube API client
youtube = build("youtube", "v3", credentials=creds)

# Sample video data — তুমি এখানে তোমার video file path, title, description, tags দিতে পারো
video_file = "video.mp4"  # Ensure this file exists in repo
request_body = {
    "snippet": {
        "title": "AI Generated Science Facts",
        "description": "Amazing 2-minute facts generated by AI!",
        "tags": ["AI", "Science", "Facts", "Automation"],
        "categoryId": "27"  # Education
    },
    "status": {
        "privacyStatus": "public",  # or unlisted/private
        "selfDeclaredMadeForKids": False,
    }
}

media = MediaFileUpload(video_file)

# Upload the video
response = youtube.videos().insert(
    part="snippet,status",
    body=request_body,
    media_body=media
).execute()

print("✅ Video uploaded successfully. Video ID:", response["id"])
